#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

if git diff --cached --name-only | grep --quiet "kafka-ui-react-app"
then
  # cd kafka-ui-react-app && npm run pre-commit
  echo "Skipping frontend tests"
else
  echo "Skipping frontend tests"
  exit 0
fi
